### ISSUE TITLE
Optimize product request on next Grocy release

### ISSUE THREAD

**Issue by BlueBlueBlob** [SebRut/pygrocy#53]
Hi
Regarding this commit  : https://github.com/grocy/grocy/commit/61a45c030f451a069975ba9c3486198c2c273290

I will do a refresh on product functions. It will clearly speed up refresh data. 

Keep in touch

**Comment by markusressel** [comment]
Cant wait for this, although the rest api seems to be quite slow in general. I am not sure if this is due to grocy or pygrocy though and currently my bet would be on grocy because it also has some seriously CPU load when querying the rest api. For me this is especially interesting since it severely limits the responsiveness when issuing commands to grocy-telegram-bot.

**Comment by BlueBlueBlob** [comment]
Already done.
