### ISSUE TITLE
prepare 1.0.0 release

### ISSUE THREAD

**Issue by SebRut** [SebRut/pygrocy#80]
Prepare 1.0.0 release to start following semver.

See #33

**Comment by BlueBlueBlob** [comment]
👍

**Comment by markusressel** [comment]
First of all: thx for the effort of building this library. I am using it to build a telegram bot for grocy and was pleased to see that I didn't have to put as much effort into the REST api communication part as I initially thought.

However, in the current state there are some things that are suboptimal when using the library as is, so I'd like to give some feedback for a potential 1.0.0 release, or a future one.

## Documentation
While most of the methods exposed by the `Grocy` class are self explanatory, I would really like to see documentation on at least **all public developer facing** methods. Especially the `get_details` parameter is quite uninformative about what it actually does, what info can be retrieved with vs. without it and what performance impact it has when using it.

## API design

### Abstraction
Since your goal is to abstract away from the original REST api data, it is confusing that there are still methods that seem to return the original REST api data put into a custom data class. An example of this would be the `volatile_stock` method which returns an `CurrentVolatilStockResponse` object (which also contains a typo :stuck_out_tongue: ). This object does not contain a list (or multiple lists) of `Product` objects, but different kinds of "responses" like `CurrentStockResponse`. I guess that this is probably the way the grocy api returns things, but imho it makes it difficult to use since although it is a product related method it does not contain `Product`s.

### Get details
I don't really understand the use case for method calls without `get_details=True`. On one hand, using `stock(False)` (which is the only option in the latest release) the `Product` items only contains an `id` without any additional information (not even the name) which would only be useful if I would manually keep a cache of all product details to compare those id's against on my side. On the other hand, querying the "details" for every product in the stock list requires lots of requests that take several seconds to complete.
Is there a better way to go about this without having to cache this information on the application side? I would really like to avoid having to remember products myself since it could cause the data states of grocy and my bot to desync over time.

### Get all products
Currently there is no way to retrieve a list of **all** products, no matter how many of them are in stock. To go around this I created a method that retrieves stock, expiring products, expired products and missing products and merges them into a single list. This is not perfect though and also has a huge impact on performance.
I would really like to have a method to simply retrieve a list of all the products defined by the user, to compare user input against.

## Performance
I have mentioned this before but wanted to mention it here again. It seems like some operations have a pretty high performance penalty, meaning they take quite some time to finish.
I have observed high CPU load on multiple, parallel processes/threads of the Grocy php instance, so there might be little this library can do about it.  Since this directly impacts the user experience I would really like to see an improvement here nonetheless, if possible.
It just baffles my mind when it takes approx. 5 seconds to retrieve a list of all the products in my grocy instance (which currently only contains about 100 items) when it is possible to retrieve thousands or even millions of data entries from an elasticsearch instance in the same amount of time :laughing: 

## Raw entities
Is there a plan to support operations on raw entities?
This could potentially give me a way to retrieve a list of all products, as mentioned above.

## Missing support
Currently there is no support for `Recipes`, `Tasks` and `Batteries`. While not critical, those should be supported at some point in time.

Thx for taking the time to read this.

**Comment by BlueBlueBlob** [comment]
Get detail : sorry I forget to parse new data model.
Should be fix with my last PR.
 But it only works for Product. Why ? Check https://demo.grocy.info/api#/

Same for performance. Grocy API related.

For generic entities and all products : https://github.com/BlueBlueBlob/pygrocydm

👍

**Comment by BlueBlueBlob** [comment]
About abstraction : clearly we need it.
For dev and users. Adding something new is not easy (I remember someone who tried to add Tasks).

So "missing support" will be after abstraction level.

Documentation too.

It's just my point of view. I'm not the boss.
And thank you for this very nice report (seriously)

**Comment by BlueBlueBlob** [comment]
Ok. I'm reworking stock stuff.
I will do a PR as a draft (I keep in mind perf and abstract)

Keep in touch 👍

**Comment by SebRut** [comment]
I think the points in this issue are either resolved or have got a separate issue tracking progress on this.
