### ISSUE TITLE
consider using ciso8601 instead of iso8601

### ISSUE THREAD

**Issue by SebRut** [SebRut/pygrocy#84]
https://pypi.org/project/ciso8601/

**Comment by jayaddison** [comment]
Hi @SebRut - I'm evaluating Python clients for `grocy` at the moment for a containerized environment.  I'd be interesting to hear the reasoning behind considering a migration to `ciso8601`, when you have time.

**Comment by SebRut** [comment]
TBH, this issue also includes evaluation. I just saw that some stuff in HA Core switched to ciso8601 because of performance reasons and was hoping to also benefit from this. Feel free to point out your concerns should there be any :)

**Comment by jayaddison** [comment]
Wow, very impressive performance improvements in https://github.com/home-assistant/core/pull/32128 .  That must be a lot of datetime parsing going on when they read through a week or so of log data :)

My concerns are minor and come from the experience of [containerizing](https://github.com/openculinary/api/commit/78a5b256408ba48367e437ef8a5958df67755a35) a Python microservice.

My goals there were to use a minimal Alpine Linux distribution, because it just makes everything easier; it's faster to download the base images, quicker to upload & run them, and has a lot of nice security properties since it's a relatively small set of software and utilities.

One thing I learned during that experience was that the Python PostgreSQL client I was using ([psycopg2](https://www.psycopg.org/)) includes a C [dependency](https://www.psycopg.org/features/) on [libpq](https://www.postgresql.org/docs/current/libpq.html) and therefore requires a C compiler at build-time.  It looks like ciso8601 is also C-based (for example, for [module.c](https://github.com/closeio/ciso8601/blob/42b7af38a619d0024be6a78be4efffcf33c749b0/module.c)) and so it would also require a C compiler during builds.

Based on all this I developed a preference for pure-Python library and migrated to [pg8000](https://github.com/tlocke/pg8000) for PostgreSQL interaction from Python.  It feels a bit safer since fewer tools, downloads, and build-time actions are required.

Unless datetime parsing/formatting become performance bottlenecks in `pygrocy` I'd suggest `ciso8601` might introduce more complexity than is necessary.

**Comment by SebRut** [comment]
No bottlenecks for now.
